/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 THIS FILE IS AUTOGENERATED BY "neira-docs/scripts/generate-sidebar.mjs"
 DO NOT EDIT THIS FILE MANUALLY
 */

const sidebars = {
  "docsSidebar": [
    {
      "type": "doc",
      "id": "README",
      "label": "Introduction"
    },
    {
      "type": "category",
      "label": "User Journeys",
      "items": [
        {
          "type": "doc",
          "id": "user-journeys/glossary",
          "label": "Glossary"
        },
        {
          "type": "doc",
          "id": "user-journeys/for-new-developer",
          "label": "For New Developer"
        },
        {
          "type": "doc",
          "id": "user-journeys/for-qa-engineer",
          "label": "For Qa Engineer"
        },
        {
          "type": "doc",
          "id": "user-journeys/for-architect",
          "label": "For Architect"
        }
      ]
    },
    {
      "type": "category",
      "label": "Getting Started",
      "items": [
        {
          "type": "doc",
          "id": "getting-started/developer-onboarding",
          "label": "Developer Onboarding"
        },
        {
          "type": "doc",
          "id": "getting-started/api-keys-configuration",
          "label": "Api Keys Configuration"
        },
        {
          "type": "doc",
          "id": "getting-started/system-compatibility",
          "label": "System Compatibility"
        }
      ]
    },
    {
      "type": "category",
      "label": "How To Guides",
      "items": [
        {
          "type": "doc",
          "id": "how-to-guides/troubleshooting-common-issues",
          "label": "Troubleshooting Common Issues"
        },
        {
          "type": "doc",
          "id": "how-to-guides/debug-mcp-integration",
          "label": "Debug Mcp Integration"
        },
        {
          "type": "doc",
          "id": "how-to-guides/using-voice-interface",
          "label": "Using Voice Interface"
        },
        {
          "type": "doc",
          "id": "how-to-guides/build-and-deploy",
          "label": "Build And Deploy"
        },
        {
          "type": "doc",
          "id": "how-to-guides/installing-chrome-extensions",
          "label": "Installing Chrome Extensions"
        },
        {
          "type": "doc",
          "id": "how-to-guides/test-workers-with-chat",
          "label": "Test Workers With Chat"
        },
        {
          "type": "doc",
          "id": "how-to-guides/working-with-logs",
          "label": "Working With Logs"
        },
        {
          "type": "doc",
          "id": "how-to-guides/run-and-debug-e2e-tests",
          "label": "Run And Debug E2e Tests"
        },
        {
          "type": "doc",
          "id": "how-to-guides/ui-performance-optimization",
          "label": "Ui Performance Optimization"
        },
        {
          "type": "doc",
          "id": "how-to-guides/mcp-reverse-ssh-tunnel",
          "label": "Mcp Reverse Ssh Tunnel"
        },
        {
          "type": "doc",
          "id": "how-to-guides/work-with-chat-hooks",
          "label": "Work With Chat Hooks"
        },
        {
          "type": "doc",
          "id": "how-to-guides/using-github-projects-for-docs",
          "label": "Using Github Projects For Docs"
        },
        {
          "type": "doc",
          "id": "how-to-guides/export-code-dumps",
          "label": "Export Code Dumps"
        },
        {
          "type": "doc",
          "id": "how-to-guides/debugging-chrome-extensions",
          "label": "Debugging Chrome Extensions"
        },
        {
          "type": "category",
          "label": "Chrome Extensions Debug",
          "items": [
            {
              "type": "doc",
              "id": "how-to-guides/chrome-extensions-debug/debug-tools",
              "label": "Debug Tools"
            },
            {
              "type": "doc",
              "id": "how-to-guides/chrome-extensions-debug/installation-issues",
              "label": "Installation Issues"
            }
          ]
        },
        {
          "type": "category",
          "label": "Troubleshooting",
          "items": [
            {
              "type": "doc",
              "id": "how-to-guides/troubleshooting/startup-and-performance",
              "label": "Startup And Performance"
            },
            {
              "type": "doc",
              "id": "how-to-guides/troubleshooting/feature-specific-issues",
              "label": "Feature Specific Issues"
            },
            {
              "type": "doc",
              "id": "how-to-guides/troubleshooting/critical-system-problems",
              "label": "Critical System Problems"
            },
            {
              "type": "doc",
              "id": "how-to-guides/troubleshooting/common-errors",
              "label": "Common Errors"
            }
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Core Concepts",
      "items": [
        {
          "type": "category",
          "label": "Architecture Patterns",
          "items": [
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/system-overview",
              "label": "System Overview"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/code-organization",
              "label": "Code Organization"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/manager-architecture",
              "label": "Manager Architecture"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/logging-strategy",
              "label": "Logging Strategy"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/polylith-backend-integration",
              "label": "Polylith Backend Integration"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/cross-platform-compatibility",
              "label": "Cross Platform Compatibility"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/security-principles",
              "label": "Security Principles"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/development-integration",
              "label": "Development Integration"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/polylith-architecture",
              "label": "Polylith Architecture"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/protobuf-architecture",
              "label": "Protobuf Architecture"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/database-architecture",
              "label": "Database Architecture"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/risk-management-overview",
              "label": "Risk Management Overview"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/risk-management",
              "label": "Risk Management"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/14b-command-validation-pattern",
              "label": "14b Command Validation Pattern"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/risk-management-patterns",
              "label": "Risk Management Patterns"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/build-security",
              "label": "Build Security"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/build-system",
              "label": "Build System"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/configuration-management",
              "label": "Configuration Management"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/interaction-diagrams",
              "label": "Interaction Diagrams"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/code-analysis",
              "label": "Code Analysis"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/stability-compatibility",
              "label": "Stability Compatibility"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/documentation-system",
              "label": "Documentation System"
            },
            {
              "type": "doc",
              "id": "core-concepts/architecture-patterns/adr-029-centralize-ai-logic-in-polylith",
              "label": "ADR 029 Centralize Ai Logic In Polylith"
            }
          ]
        },
        {
          "type": "category",
          "label": "Shell Core",
          "items": [
            {
              "type": "doc",
              "id": "core-concepts/shell-core/shell-architecture",
              "label": "Shell Architecture"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/electron-principles",
              "label": "Electron Principles"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/api-management",
              "label": "Api Management"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/05-ipc-architecture",
              "label": "Ipc Architecture"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/command-security",
              "label": "Command Security"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/logging-system",
              "label": "Logging System"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/mcp-architecture",
              "label": "Mcp Architecture"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/chrome-web-store-integration",
              "label": "Chrome Web Store Integration"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/error-handling",
              "label": "Error Handling"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/logger-architecture",
              "label": "Logger Architecture"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/tab-management",
              "label": "Tab Management"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/file-watching-implementation",
              "label": "File Watching Implementation"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/file-watching",
              "label": "File Watching"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/07-workers-architecture",
              "label": "Workers Architecture"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/10.1-e2e-livelock-fix",
              "label": "10.1 E2e Livelock Fix"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/note-e2e-livelock-fix",
              "label": "Note E2e Livelock Fix"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/proto-contracts",
              "label": "Proto Contracts"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/file-watching-system",
              "label": "File Watching System"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/automation-engine",
              "label": "Automation Engine"
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/browser-session-and-authentication",
              "label": "Session Management"
            },
            {
              "type": "category",
              "label": "Chrome Extensions",
              "items": [
                {
                  "type": "doc",
                  "id": "core-concepts/shell-core/chrome-extensions/updater-service",
                  "label": "Updater Service"
                },
                {
                  "type": "doc",
                  "id": "core-concepts/shell-core/chrome-extensions/storage-api",
                  "label": "Storage Api"
                },
                {
                  "type": "doc",
                  "id": "core-concepts/shell-core/chrome-extensions/ui-integration",
                  "label": "Ui Integration"
                },
                {
                  "type": "doc",
                  "id": "core-concepts/shell-core/chrome-extensions/missing-apis",
                  "label": "Missing Apis"
                }
              ]
            },
            {
              "type": "doc",
              "id": "core-concepts/shell-core/chrome-web-store-architecture",
              "label": "Chrome Web Store Architecture"
            },
            {
              "type": "category",
              "label": "Ipc Architecture",
              "items": [
                {
                  "type": "doc",
                  "id": "core-concepts/shell-core/ipc-architecture/channel-groups-basics",
                  "label": "Channel Groups Basics"
                },
                {
                  "type": "doc",
                  "id": "core-concepts/shell-core/ipc-architecture/proto-generation",
                  "label": "Proto Generation"
                }
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "Ui Layer",
          "items": [
            {
              "type": "doc",
              "id": "core-concepts/ui-layer/chat-architecture",
              "label": "Chat Architecture"
            },
            {
              "type": "doc",
              "id": "core-concepts/ui-layer/navigation-architecture",
              "label": "Navigation Architecture"
            },
            {
              "type": "doc",
              "id": "core-concepts/ui-layer/design-theming",
              "label": "Design Theming"
            },
            {
              "type": "doc",
              "id": "core-concepts/ui-layer/thinking-indicator",
              "label": "Thinking Indicator"
            },
            {
              "type": "doc",
              "id": "core-concepts/ui-layer/neira-app-architecture",
              "label": "Neira App Architecture"
            },
            {
              "type": "doc",
              "id": "core-concepts/ui-layer/chat-streaming-lifecycle",
              "label": "Chat Streaming Lifecycle"
            },
            {
              "type": "doc",
              "id": "core-concepts/ui-layer/18-code-editor",
              "label": "Code Editor"
            },
            {
              "type": "doc",
              "id": "core-concepts/ui-layer/layout-and-window-management",
              "label": "Layout And Window Management"
            },
            {
              "type": "doc",
              "id": "core-concepts/ui-layer/chat-core",
              "label": "Chat Core"
            },
            {
              "type": "doc",
              "id": "core-concepts/ui-layer/chat-state",
              "label": "Chat State"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ai Engine",
          "items": [
            {
              "type": "doc",
              "id": "core-concepts/ai-engine/ai-architecture",
              "label": "Ai Architecture"
            },
            {
              "type": "doc",
              "id": "core-concepts/ai-engine/planner-service",
              "label": "Planner Service"
            },
            {
              "type": "doc",
              "id": "core-concepts/ai-engine/voice-audio",
              "label": "Voice Audio"
            },
            {
              "type": "doc",
              "id": "core-concepts/ai-engine/proxy-ai-server",
              "label": "Proxy Ai Server"
            },
            {
              "type": "doc",
              "id": "core-concepts/ai-engine/17-python-integration",
              "label": "Python Integration"
            },
            {
              "type": "doc",
              "id": "core-concepts/ai-engine/22-grpc-api-reference",
              "label": "Grpc Api Reference"
            },
            {
              "type": "doc",
              "id": "core-concepts/ai-engine/python-troubleshooting",
              "label": "Python Troubleshooting"
            },
            {
              "type": "doc",
              "id": "core-concepts/ai-engine/grpc-troubleshooting",
              "label": "Grpc Troubleshooting"
            },
            {
              "type": "doc",
              "id": "core-concepts/ai-engine/24-grpc-methods-reference",
              "label": "Grpc Methods Reference"
            },
            {
              "type": "doc",
              "id": "core-concepts/ai-engine/python-agent-setup",
              "label": "Python Agent Setup"
            },
            {
              "type": "doc",
              "id": "core-concepts/ai-engine/python-grpc-api",
              "label": "Python Grpc Api"
            }
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Reference",
      "items": [
        {
          "type": "doc",
          "id": "reference/chrome-extensions",
          "label": "Chrome Extensions"
        },
        {
          "type": "doc",
          "id": "reference/openrouter-integration",
          "label": "Openrouter Integration"
        },
        {
          "type": "doc",
          "id": "reference/code-editor",
          "label": "Code Editor"
        },
        {
          "type": "doc",
          "id": "reference/mcp-integration",
          "label": "Mcp Integration"
        },
        {
          "type": "doc",
          "id": "reference/chrome-web-store",
          "label": "Chrome Web Store"
        },
        {
          "type": "doc",
          "id": "reference/native-messaging-host",
          "label": "Native Messaging Host"
        },
        {
          "type": "doc",
          "id": "reference/state-management",
          "label": "State Management"
        },
        {
          "type": "doc",
          "id": "reference/ui-and-design",
          "label": "Ui And Design"
        },
        {
          "type": "doc",
          "id": "reference/crx3-parser-guide",
          "label": "Crx3 Parser Guide"
        }
      ]
    },
    {
      "type": "category",
      "label": "Contributing",
      "items": [
        {
          "type": "doc",
          "id": "contributing/style-guide",
          "label": "Style Guide"
        },
        {
          "type": "doc",
          "id": "contributing/golden-principles",
          "label": "Golden Principles"
        },
        {
          "type": "doc",
          "id": "contributing/development-checklist",
          "label": "Development Checklist"
        },
        {
          "type": "doc",
          "id": "contributing/code-quality-checks",
          "label": "Code Quality Checks"
        },
        {
          "type": "doc",
          "id": "contributing/documentation-lifecycle",
          "label": "Documentation Lifecycle"
        },
        {
          "type": "doc",
          "id": "contributing/auto-rules-generation",
          "label": "Auto Rules Generation"
        },
        {
          "type": "doc",
          "id": "contributing/code-quality-standards",
          "label": "Code Quality Standards"
        },
        {
          "type": "doc",
          "id": "contributing/managing-scripts-lifecycle",
          "label": "Managing Scripts Lifecycle"
        },
        {
          "type": "doc",
          "id": "contributing/polylith-migration-roadmap",
          "label": "Polylith Migration Roadmap"
        },
        {
          "type": "doc",
          "id": "contributing/repository-management",
          "label": "Repository Management"
        },
        {
          "type": "doc",
          "id": "contributing/next-development-priorities",
          "label": "Next Development Priorities"
        },
        {
          "type": "doc",
          "id": "contributing/test-the-application",
          "label": "Test The Application"
        },
        {
          "type": "doc",
          "id": "contributing/tests-reviewer-guide",
          "label": "Tests Reviewer Guide"
        },
        {
          "type": "doc",
          "id": "contributing/dependency-management",
          "label": "Dependency Management"
        },
        {
          "type": "doc",
          "id": "contributing/qa-roadmap",
          "label": "Qa Roadmap"
        },
        {
          "type": "doc",
          "id": "contributing/release-notes-process",
          "label": "Release Notes Process"
        },
        {
          "type": "doc",
          "id": "contributing/extension-security-guidelines-new",
          "label": "Extension Security Guidelines New"
        },
        {
          "type": "doc",
          "id": "contributing/extension-security-guidelines",
          "label": "Extension Security Guidelines"
        },
        {
          "type": "doc",
          "id": "contributing/code-audit-resolutions-2025-07",
          "label": "Code Audit Resolutions 2025 07"
        },
        {
          "type": "doc",
          "id": "contributing/circular-dependency-prevention",
          "label": "Circular Dependency Prevention"
        },
        {
          "type": "doc",
          "id": "contributing/security-best-practices",
          "label": "Security Best Practices"
        },
        {
          "type": "doc",
          "id": "contributing/CONTRIBUTING",
          "label": "CONTRIBUTING"
        }
      ]
    },
    {
      "type": "category",
      "label": "Api Reference",
      "items": [
        {
          "type": "doc",
          "id": "api-reference/web-api",
          "label": "Web Api"
        }
      ]
    },
    {
      "type": "doc",
      "id": "README",
      "label": "README"
    },
    {
      "type": "category",
      "label": "Neira Core",
      "items": [
        {
          "type": "doc",
          "id": "neira-core/README",
          "label": "README"
        }
      ]
    },
    {
      "type": "category",
      "label": "Neira Enterprise",
      "items": [
        {
          "type": "doc",
          "id": "neira-enterprise/README",
          "label": "README"
        }
      ]
    }
  ]
};

export default sidebars;
